version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "dog/package.json" }}
            - v1-dependencies-

      - run:
          command: yarn install
          working_directory: dog

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "dog/package.json" }}

      - run:
          command: yarn test
          working_directory: dog

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
